enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config




[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
arch = "arm64-v8a"
included-patches = "'SIM spoof'"
excluded-patches = "'Downloads' 'Remember clear display' 'Feed filter'"


[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
included-patches = "'Hide inbox ads'"
exclusive-patches = true

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"

[reddit.news]
apkmirror-dlurl = "https://www.apkmirror.com/apk/dbrady/relay-for-reddit-2/"
version = "10.2.40"
        
[
  {
    "patchName": "Spoof client",
    "options": [
      {
        "key": "client-id",
        "value": "vaTEHI59TI1lQN1hrKkFpQ"
      }
    ]
  }
]
        

[Google Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"

[Lightroom Photo & Video Editor]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
arch = "arm64-v8a"

